#!/usr/bin/env python2.7
# addSpace
# Chris Eisenhart 04/28/2015
"""
This progroam takes any text in sys.stdin and prints the text to sys.stdOut with a extra
new line between each line. Helpful for picky formatting. 
"""
from __future__ import print_function  
import  sys, operator, fileinput, collections, string, os.path
import  re, argparse, random


def parseArgs(args): 
    """
    Set the specifications for user provided options. The following 
    options are supported, 
    """
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument ("--verbose", "-v",
    help = " Print individual simulation statistics and all default conditions",
    action = "store_true")
    parser.set_defaults (verbose = False)
    options = parser.parse_args()
    return options

def main(args):
    """
    Reads in the user commands and options, opening
    any files if necessary otherwise reading from sys.stdin. 
    """
    options = parseArgs(args)
    if options.verbose:
        print(options.verbose, options.columnOrder)
    for line in sys.stdin:
        print (line)
        print ()

if __name__ == "__main__" :
    sys.exit(main(sys.argv))
