#!/bin/bash

usage()
{
    echo "hideDesktop - Hides/unhides all the icons on the desktop.
usage:
    hideDesktop hide    Hide the desktop
    hideDekstop hide reverse    Unhide the desktop
" 1>&2
}

if [ $# -lt 1 ]; then
    usage
    exit 255
fi

if [ $# -lt 2 ]; then
    defaults write com.apple.finder CreateDesktop false
    killall Finder 
    exit 255
fi

if [ $# -gt 1 ]; then
    defaults write com.apple.finder CreateDesktop true
    killall Finder 
    exit 255
fi
